apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-prod-cert
  namespace: asm-ingress
spec:
  secretName: ingress-prod-cert
  commonName: whereami.alexmattson.demo.altostrat.com
  issuerRef:
    # The issuer created previously
    name: ingressgateway-prod-issuer
  dnsNames:
  - whereami.alexmattson.demo.altostrat.com # replace with your values